### ISSUE TITLE
Global Dashboard vs regular one view connections

### ISSUE THREAD

**Issue by zeshan1977** [HewlettPackard/oneview-samples#1]
Is it possible to connect  to Global DashBoard rather than oneView with the Python SDK?.

Code>>
import sys
from pprint import pprint
from hpOneView.oneview_client import OneViewClient

config = {
         "ip": sys.argv[1],
         "credentials": {
             "userName":"readonly",
             "password":"readonly",
             "authLoginDomain":"local"
         }
}

oneview_client = OneViewClient(config)

print("Get the current version and the minimum version")
version = oneview_client.versions.get_version()
pprint(version)
#EndCODE

>>ISSUE
the above code when run with an IP of the dashboard, gets the error
python versions.py 19.14.83.XXX

Traceback (most recent call last):
  File "versions.py", line 32, in <module>
    oneview_client = OneViewClient(config)
  File "C:\Users\MZESHAN\AppData\Local\Continuum\Anaconda3-5.2.0\lib\site-packages\hpOneView\oneview_client.py", line 122, in __init__
    self.__connection.login(config["credentials"])
  File "C:\Users\MZESHAN\AppData\Local\Continuum\Anaconda3-5.2.0\lib\site-packages\hpOneView\connection.py", line 458, in login
    task, body = self.post(uri['loginSessions'], self._cred)
  File "C:\Users\MZESHAN\AppData\Local\Continuum\Anaconda3-5.2.0\lib\site-packages\hpOneView\connection.py", line 377, in post
    return self.__do_rest_call('POST', uri, body, custom_headers=custom_headers)
  File "C:\Users\MZESHAN\AppData\Local\Continuum\Anaconda3-5.2.0\lib\site-packages\hpOneView\connection.py", line 404, in __do_rest_call
    raise HPOneViewException(body)
hpOneView.exceptions.HPOneViewException: ('The API version information is absent or invalid.', {'errorCode': 'INVALID_API_VERSION', 'message': 'The API version information is absent or invalid.', 'recommendedActions': ['Refer to the API specification to determine the supported API versions.'], 'details': "The request did not contain a valid 'x-api-version' header.", 'errorSource': None, 'nestedErrors': [], 'data': [], 'canForce': False})

>>The code when run with a OneView Dashboard IP:
Get the current version and the minimum version
{'currentVersion': 1200, 'minimumVersion': 120}

**Comment by ChrisLynchHPE** [comment]
Sorry for replying so late to this issue, but this tracker is not for the SDK's.  Please post this question on the [Python SDK issue tracker](https://github.com/HewlettPackard/python-hponeview/issues).
